---
exclude: ['README.markdown']
permalink: ':title'
highlighter: rouge
markdown: kramdown
safe: false
title: 'Spiral Framework'
source: 'web'

defaults:
  -
    scope:
      path: ""
    values:
      is_post: true